apiVersion: v1
kind: Namespace
metadata:
  name: gemma-serverless
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models-pvc
  namespace: gemma-serverless
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
